# AQQBot 配置文件
# 可使用 /aqqbot reload 重载

# 存储相关配置 (重启后生效)
storage:
  # 存储方式
  # 可选方式: file, sqlite, mysql
  type: "file"

  # SQLite 数据库配置
  sqlite:
    file: "aqqbot.db"

  # MySQL 数据库配置
  mysql:
    host: "127.0.0.1"
    port: 3306
    user: "root"
    password: "123456"
    database: "aqqbot"

# 添加白名单
whitelist:
  # 是否启用该功能
  enable: true

  # 是否必须绑定后才能进入游戏
  need_bind_to_login: true

  # 功能指令前缀
  prefix:
    # 绑定指令前缀
    # 用户需要发送的消息: $command $name
    bind:
      - "/绑定"
      - "/bind"

    # 解绑指令前缀
    # 用户需要发送的消息: $command $name
    unbind:
      - "/解绑"
      - "/unbind"

  # 是否启用管理员管理
  # 管理员可通过/${prefix} $userId $name 进行绑定/解绑
  admin: true

# 查询服务器基本信息
# 需要安装 spark 插件作为前置 (部分paper(包括下游)服务端内置, 后台执行 spark 若有反应则说明内置)
information:
  # 功能: 查询服务器TPS 输出结果:
  # 服务器TPS: ${tps_5_seconds}, ${tps_10_seconds}, ${tps_1_min}, ${tps_5_min}, ${tps_15_min}
  tps:
    # 是否启用该功能
    enable: true

    # 获取指令
    command:
      - "/tps"
      - "tps"
      - "服务器tps"
      - "/服务器tps"

  # 功能: 查询服务器在线玩家 输出结果:
  # 服务器在线玩家(${amount}): ${player_list}
  list:
    # 是否启用该功能
    enable: true

    # 获取指令
    command:
      - "/list"
      - "list"
      - "在线玩家"
      - "/在线玩家"
      - "服务器在线玩家"
      - "/服务器在线玩家"

  # 功能: 查看服务器CPU占用信息 输出结果:
  # 服务器CPU占用率: ${cpu_10_seconds}, ${cpu_1_min}, ${cpu_15_min}
  cpu:
    # 是否启用该功能
    enable: true

    # 获取指令
    command:
      - "/cpu"
      - "cpu"
      - "服务器cpu"
      - "/服务器cpu"
      - "cpu占用率"
      - "/cpu占用率"

  # 功能: 查看服务器MSPT(均为平均值) 输出结果:
  # 服务器MSPT: ${mspt_10_seconds}, ${mspt_1_min}, ${mspt_15_min}
  mspt:
    # 是否启用该功能
    enable: true

    # 获取指令
    command:
      - "/mspt"
      - "mspt"
      - "服务器mspt"
      - "/服务器mspt"

# 聊天(群服互联)功能
# * 该功能仅支持Bukkit类服务端
chat:
  # 群->服聊天转发功能 转发结果:
  # [QQ群(${groupId})] ${sender}: ${message}
  group_to_server:
    # 是否启用该功能
    enable: true

    # 若转发, 需要发送什么作为前缀的消息 (空代表不需要前缀)
    prefix:
      - ""

  # 服->群聊天转发功能 转发结果:
  # [服务器] ${sender}: ${message}
  server_to_group:
    # 是否启用该功能
    enable: true

    # 若转发, 需要发送什么作为前缀的消息 (空代表不需要前缀)
    prefix:
      - ""

# 服务器开启/关闭通知
notify:
  # 是否开启该功能
  enable: true

  # 通知信息:
  messages:
    # 开启时:
    start: "[AQQBot] XXX服务器已启动!"

    # 关闭时:
    stop: "[AQQBot] XXX服务器已关闭!"

# 服务器命令远程执行
# * 该功能仅支持Bukkit类服务端
# 通过在QQ发送指定前缀消息来执行服务器命令
# 执行命令时, 不需要再加 / 号, 只需要填写命令前缀
# 如: 在游戏里执行 /spark health -> 在QQ群内执行 /sudo spark health
command_execution:
  # 是否启用该功能
  enable: true

  # 允许使用该功能的人
  # $ADMIN 代表所有管理员
  # $OWNER 代表群主
  # $USER 代表所有用户
  # 范围覆盖: $USER > $ADMIN > $OWNER
  # 如果你想指定除了这里的人以外的特定用户, 你可填写用户的QQ号到这里
  allow:
    - "$ADMIN"

  # 指令前缀
  prefix:
    - "/sudo"
    - "/执行"

  # 是否格式化消息 (将颜色符号去除)
  # 默认包含 §0, §1 , ... , §9, §a, ..., §f, §k, §l, §m, §n, §o, §r
  format: true

  # 特定格式化 (将以下列表中的符号去除) 不需要开启格式化消息选项即可使用
  # 如: 在列表中含有 "§x" 则将 "§xA§xB" 转换为 "AB"
  # 只填写 "" (如下) 代表不进行特定格式化
  format_list:
    - ""

  # 等待输出结果多长时间
  # 单位: 秒
  delay: 2
